---
- name: Install {{ _name }} dependencies
  ansible.builtin.apt:
    pkg:
      - python3-pip
      # - python3-pip-whl
      - python3-six
      - python3-setuptools
      - python3-venv
      # - python3-build
      - python3-virtualenv
      - python3-argcomplete
      # - python3-poetry
      - python3-ipython
      - python3-ipdb
    state: present
    update_cache: true
  become: true
  when: "ansible_os_family == 'Debian'"

- name: Install {{ _name }} packages
  ansible.builtin.pip:
    name: "{{ item }}"
    umask: "0022"
    # extra_args: --break-system-packages
  loop:
    - pynvim
    - pipx
    - git+https://git.ars-virtualis.org/yul/lsfiles@master
    - git+https://git.ars-virtualis.org/yul/utils@master
  when: "ansible_os_family == 'Debian'"
  become: true

- name: Install {{ _name }} packages
  ansible.builtin.pip:
    name: "{{ item }}"
    umask: "0022"
  loop:
    - pynvim
    - pipx
    - git+https://git.ars-virtualis.org/yul/lsfiles@master
    - git+https://git.ars-virtualis.org/yul/utils@master
  when: "ansible_os_family == 'Darwin'"
  become: true

# hardcoded PATH, either install globally or find a better way
- name: Update PATH
  ansible.builtin.lineinfile:
    path: /etc/zsh/zshenv
    line: "export {{ item }}"
  loop:
    - "PIPX_HOME={{ _tooldir }}/pipx"
    - "PIPX_BIN_DIR=$PIPX_HOME/bin"
    - "PATH=$PIPX_BIN_DIR:$PATH"
    - "IPYTHONDIR=$DOTFILES/ipython"
  when: "ansible_os_family == 'Debian'"
  become: true

# hardcoded PATH, either install globally or find a better way
- name: Update PATH
  ansible.builtin.lineinfile:
    path: /etc/zshenv
    line: "export {{ item }}"
  loop:
    - "PIPX_HOME=$TOOLDIR/pipx"
    - "PIPX_BIN_DIR=$PIPX_HOME/bin"
    - "PATH=$PIPX_BIN_DIR:$PATH"
    - "IPYTHONDIR=$DOTFILES/ipython"
  when: "ansible_os_family == 'Darwin'"
  become: true

- name: Install dev packages
  ansible.builtin.shell: |
    pipx install git+https://github.com/tmux-python/tmuxp && \
    pipx inject tmuxp git+https://git.ars-virtualis.org/yul/tmuxp-plugin-loader
  changed_when: false
  become: true

# - name: Install deadsnakes PPA
#   ansible.builtin.shell: |
#     add-apt-repository ppa:deadsnakes/ppa -y && \
#     apt-get update
#   when: "ansible_os_family == 'Debian' and ansible_distribution_major_version < 23"
#   become: true
