---
- name: Install dependencies
  ansible.builtin.apt:
    pkg:
      - cmake
      - ninja-build
      - libpcre3
      - libpcre3-dev
      - libboost-dev
    state: present
    update_cache: true
  become: true

- name: "Clone {{ _name }} branch {{ _branch }}"
  ansible.builtin.git:
    repo: "{{ _repo }}"
    dest: "{{ _src }}"
    version: "{{ _branch }}"
    depth: 1
    single_branch: true
  register: git_result

# stagging
- name: "Stage {{ _name }}"
  ansible.builtin.file:
    path: "{{ _build }}"
    mode: 0755
    state: directory

- name: "Configure {{ _name }}"
  ansible.builtin.shell: |
    cmake -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX={{ _prefix }} \
        -DREGISTER_TESTS=OFF \
        -DENABLE_OSS_FUZZ=OFF \
        -DHAVE_RULES=ON \
        -DUSE_MATCHCOMPILER=ON \
        -DUSE_BOOST=ON \
        ..
  args:
    chdir: "{{ _build }}"
  changed_when: false

# build
- name: "Build {{ _name }}"
  ansible.builtin.shell: |
    ninja
  args:
    chdir: "{{ _build }}"
  changed_when: false

# install
- name: "Install {{ _name }}"
  ansible.builtin.shell: |
    ninja install
  args:
    chdir: "{{ _build }}"
  changed_when: false
  become: true

# clean
# - name: "Clean {{ _name }}"
#   ansible.builtin.file:
#     path: "{{ _build }}"
#     state: absent

- name: "Delete pre-existing {{ _name }} repo"
  ansible.builtin.file:
    path: "{{ _src }}"
    state: absent
