---
- name: Update npm
  ansible.builtin.shell: |
    npm install npm@latest -g
  changed_when: false
  become: true

- name: Update npm packages
  ansible.builtin.shell: |
    npm update -g
  changed_when: false
  become: true
