---
- name: Copy avahi-daemon.conf
  ansible.builtin.template:
    src: avahi-daemon.conf.j2
    dest: /etc/avahi/avahi-daemon.conf
    owner: "{{ ansible_become_user }}"
    mode: '0644'
  register: config
  become: true

- name: Restart service
  ansible.builtin.systemd:
    state: restarted
    name: avahi-daemon
  when: config.changed
  become: true
