---
- name: Debug
  ansible.builtin.debug:
    msg:
      - "inventory_hostname={{ inventory_hostname }}"
      - "{{ hostvars[inventory_hostname] }}"
      # - "ansible_connection={{ ansible_connection }}"
      # - "ansible_user={{ ansible_user }}"
      # - "ansible_become_user={{ ansible_become_user }}"
      # - "ansible_become_pass={{ ansible_become_pass }}"
      # - "ansible_python_interpreter={{ ansible_python_interpreter }}"
      # - "ansible_shell_executable={{ ansible_shell_executable }}"

- name: Uninstall previous
  ansible.builtin.apt:
    pkg:
      - vagrant
    state: absent
    update_cache: true
  become: true

- name: Download GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /tmp/hashicorp-archive-keyring.gpg
    mode: '0700'
  become: true

- name: "Install GPG - key"
  ansible.builtin.shell: |
    gpg --dearmor < /tmp/hashicorp-archive-keyring.gpg > /usr/share/keyrings/hashicorp-archive-keyring.gpg
  changed_when: false
  become: true

- name: "Install repo"
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/hashicorp.list
    line: |
      deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    owner: root
    mode: '0644'
    create: true
  become: true

- name: "Install"
  ansible.builtin.apt:
    pkg:
      - vagrant
    state: present
    update_cache: true
  become: true
