---
- name: Clean {{ _name }} pip cache
  ansible.builtin.shell: |
    "{{ ansible_python_interpreter }}" -m pip cache purge
  changed_when: false
  become: true

- name: Clean python temporary files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/{{ ansible_become_user }}/.python_history"
    - "/{{ ansible_user }}/.python_history"
  become: true
